/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova.view;

import edunova.controller.ObradaIskaz;
import edunova.model.Artikal;
import edunova.model.Djelatnik;
import edunova.model.Iskaz;
import edunova.util.Alati;
import edunova.util.EdunovaException;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import edunova.util.HibernateUtil;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hibernate.HibernateException;

/**
 *
 * @author goran
 */
public class ProzorIskaz extends javax.swing.JFrame {

       
    private SessionFactory sessionFactory;
    private ObradaIskaz obrada;

    public ProzorIskaz() {
        initComponents();
        obrada = new ObradaIskaz();
        setTitle(Alati.NAZIV_APP + " | ISKAZ");

        // Inicijalizacija SessionFactory
        sessionFactory = HibernateUtil.getSessionFactory();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPodaci = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtArtikal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDjelatnik = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lstPodaci);

        jLabel2.setText("Datum");

        txtDatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatumKeyPressed(evt);
            }
        });

        jLabel3.setText("Artikal");

        txtArtikal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtArtikalKeyPressed(evt);
            }
        });

        jLabel4.setText("Djelatnik");

        txtDjelatnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDjelatnikActionPerformed(evt);
            }
        });
        txtDjelatnik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDjelatnikKeyPressed(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArtikal, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtDjelatnik, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDodaj)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDjelatnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnDodaj)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         txtDjelatnik.requestFocus();
    }//GEN-LAST:event_txtDatumKeyPressed

    private void txtArtikalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArtikalKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         btnDodaj.requestFocus();
    }//GEN-LAST:event_txtArtikalKeyPressed

    private void txtDjelatnikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDjelatnikKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         txtArtikal.requestFocus();
    }//GEN-LAST:event_txtDjelatnikKeyPressed

    private void txtDjelatnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDjelatnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDjelatnikActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

    try {
            // Dobivanje podataka iz korisničkog sučelja
            String datum = txtDatum.getText();
            String djelatnik = txtDjelatnik.getText();
            String artikal = txtArtikal.getText();

            // Provjera jesu li svi podaci uneseni
            if (datum.isEmpty() || djelatnik.isEmpty() || artikal.isEmpty()) {
                throw new EdunovaException("Svi podaci moraju biti uneseni");
            }

            // Kreiranje novog objekta Iskaz s unesenim podacima
            Iskaz iskaz = new Iskaz();
            iskaz.setDatum(datum);
            iskaz.setDjelatnik(djelatnik);
            iskaz.setArtikal(artikal);

            // Otvorite Hibernate session
            Session session = HibernateUtil.getSession();

            // Počnite transakciju
            session.beginTransaction();

            // Unos iskaza u bazu podataka pomoću Hibernatea
            session.save(iskaz);

            // Završite transakciju
            session.getTransaction().commit();

            // Zatvorite Hibernate session
            HibernateUtil.zatvoriSession(session);

        
            // Obavijestite korisnika o uspješnom unosu
            JOptionPane.showMessageDialog(this, "Iskaz je uspješno spremljen u bazu.");
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(this, "Greška prilikom unosa iskaza: " + e.getMessage());
        }
    }

    private static class txtDatum {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtDatum() {
        }
    }

    private static class txtDjelatnik {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtDjelatnik() {
        }
    }

    private static class txtArtikal {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtArtikal() {
        }
    



        
    }//GEN-LAST:event_btnDodajActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Iskaz> lstPodaci;
    private javax.swing.JTextField txtArtikal;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDjelatnik;
    // End of variables declaration//GEN-END:variables

  
}
