/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova.view;
import javax.swing.JOptionPane;
import edunova.util.Alati;
import edunova.model.Artikal;
import edunova.util.HibernateUtil;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
/**
 *
 * @author goran
 */
public class ProzorArtikal extends javax.swing.JFrame {

    private BigDecimal cijenaBigDecimal;

    /**
     * Creates new form ProzorArtikal
     */
    public ProzorArtikal() {
        initComponents();
        setTitle(Alati.NAZIV_APP+ " | Artikal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv");

        txtNaziv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNazivKeyPressed(evt);
            }
        });

        jLabel2.setText("Cijena");

        txtNaziv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNaziv1KeyPressed(evt);
            }
        });

        jLabel3.setText("Jedinica Mjere");

        txtNaziv2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNaziv2KeyPressed(evt);
            }
        });

        jButton1.setText("Spremi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(166, 166, 166))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNaziv2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaziv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaziv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivKeyPressed

        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         txtNaziv1.requestFocus();
    }//GEN-LAST:event_txtNazivKeyPressed

    private void txtNaziv1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNaziv1KeyPressed
      
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         txtNaziv2.requestFocus();
        
    }//GEN-LAST:event_txtNaziv1KeyPressed

    private void txtNaziv2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNaziv2KeyPressed
       
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         jButton1.requestFocus();
        
    }//GEN-LAST:event_txtNaziv2KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                                                
    // Unos podataka iz korisničkog sučelja
    String naziv = txtNaziv.getText();
    //double cijena = Double.parseDouble(txtNaziv1.getText());
    //String jedinicaMjere = txtNaziv2.getText();

       
    
    //System.out.println("Unesena cijena: " + cijena);
    
    //cijenaBigDecimal = BigDecimal.valueOf(cijena);
    
    // Stvaranje objekta Artikal
    Artikal artikal = new Artikal();
    artikal.setNaziv(naziv);
    //artikal.setCijena(cijenaBigDecimal);
    //artikal.setJedinicaMjere(jedinicaMjere);
    
      
    // Spremanje objekta u bazu podataka pomoću Hibernatea
    try {
        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        try (Session session = sessionFactory.openSession()) {
            session.beginTransaction();
            
            session.save(artikal); // Spremi artikal u bazu podataka
            
            session.getTransaction().commit();
        }

        JOptionPane.showMessageDialog(this, "Artikal uspješno spremljen u bazu.");
    } catch (HeadlessException | HibernateException e) {
        JOptionPane.showMessageDialog(this, "Greška prilikom spremanja artikla: " + e.getMessage());
    }

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtNaziv1;
    private javax.swing.JTextField txtNaziv2;
    // End of variables declaration//GEN-END:variables
}
