/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova.view;


import edunova.model.Artikal;
import edunova.model.Djelatnik;
import edunova.model.Iskaz;
import javax.swing.JOptionPane;
import edunova.util.Alati;
import edunova.util.EdunovaException;
import edunova.util.HibernateUtil;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author goran
 */
public class ProzorIskaz extends javax.swing.JFrame {

   
    public ProzorIskaz() {
        initComponents();
        setTitle(Alati.NAZIV_APP + " | ISKAZ");

     }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPodaci = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtArtikal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDjelatnik = new javax.swing.JTextField();
        JButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lstPodaci);

        jLabel2.setText("Datum");

        txtDatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatumKeyPressed(evt);
            }
        });

        jLabel3.setText("Artikal");

        txtArtikal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtArtikalKeyPressed(evt);
            }
        });

        jLabel4.setText("Djelatnik");

        txtDjelatnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDjelatnikActionPerformed(evt);
            }
        });
        txtDjelatnik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDjelatnikKeyPressed(evt);
            }
        });

        JButtom.setText("Dodaj");
        JButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArtikal, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtDjelatnik, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtom)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDjelatnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(JButtom)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         txtDjelatnik.requestFocus();
    }//GEN-LAST:event_txtDatumKeyPressed

    private void txtArtikalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArtikalKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         JButtomActionPerformed(null);
    }//GEN-LAST:event_txtArtikalKeyPressed

    private void txtDjelatnikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDjelatnikKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER)
                         txtArtikal.requestFocus();
    }//GEN-LAST:event_txtDjelatnikKeyPressed

    private void txtDjelatnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDjelatnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDjelatnikActionPerformed

    private void JButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtomActionPerformed
                                       
   
 
    String datumString = txtDatum.getText();
    Date datum = null; // Datum kao java.util.Date
    int djelatnikId = Integer.parseInt(txtDjelatnik.getText());
    int artikalId = Integer.parseInt(txtArtikal.getText());

      
   // Pretvaranje datuma iz Stringa u Date
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        datum = sdf.parse(datumString);
    } catch (ParseException ex) {
        // Obrada iznimke ako je String neispravan datum
        ex.printStackTrace();
    }

    // Stvaranje objekta Iskaz
    Iskaz iskaz = new Iskaz();
    iskaz.setDatum(datum);
    iskaz.setDjelatnikId(djelatnikId);
    iskaz.setArtikalId(artikalId);

    // Spremanje objekta u bazu podataka pomoću Hibernatea
    try {
        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        try (Session session = sessionFactory.openSession()) {
            session.beginTransaction();

            session.save(iskaz); // Spremi iskaz u bazu podataka

            session.getTransaction().commit();
        }

        JOptionPane.showMessageDialog(this, "Iskaz uspješno spremljen u bazu.");
    } catch (HeadlessException | HibernateException e) {
        JOptionPane.showMessageDialog(this, "Greška prilikom spremanja iskaza: " + e.getMessage());
    }
           
    }//GEN-LAST:event_JButtomActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Iskaz> lstPodaci;
    private javax.swing.JTextField txtArtikal;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDjelatnik;
    // End of variables declaration//GEN-END:variables

    private void ucitaj() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

  
}
